# CMake generated Testfile for 
# Source directory: /Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests
# Build directory: /Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/build_debug/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
include("/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/build_debug/tests/test_field_registry[1]_include.cmake")
include("/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/build_debug/tests/test_parser_fields[1]_include.cmake")
include("/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/build_debug/tests/test_community_correlation[1]_include.cmake")
add_test(test_pcapng_reader "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/build_debug/tests/test_pcapng_reader")
set_tests_properties(test_pcapng_reader PROPERTIES  LABELS "unit" TIMEOUT "30" _BACKTRACE_TRIPLES "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;33;add_test;/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;0;")
add_test(test_gtpv1_parser "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/build_debug/tests/test_gtpv1_parser")
set_tests_properties(test_gtpv1_parser PROPERTIES  LABELS "unit" TIMEOUT "30" _BACKTRACE_TRIPLES "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;54;add_test;/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;0;")
add_test(test_sctp_parser "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/build_debug/tests/test_sctp_parser")
set_tests_properties(test_sctp_parser PROPERTIES  LABELS "unit" TIMEOUT "30" _BACKTRACE_TRIPLES "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;73;add_test;/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;0;")
add_test(test_s1ap_parser "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/build_debug/tests/test_s1ap_parser")
set_tests_properties(test_s1ap_parser PROPERTIES  LABELS "unit" TIMEOUT "30" _BACKTRACE_TRIPLES "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;92;add_test;/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;0;")
add_test(test_nas_parser "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/build_debug/tests/test_nas_parser")
set_tests_properties(test_nas_parser PROPERTIES  LABELS "unit" TIMEOUT "30" _BACKTRACE_TRIPLES "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;111;add_test;/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;0;")
add_test(test_diameter_base "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/build_debug/tests/test_diameter_base")
set_tests_properties(test_diameter_base PROPERTIES  LABELS "unit" TIMEOUT "30" _BACKTRACE_TRIPLES "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;130;add_test;/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;0;")
add_test(test_diameter_gx "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/build_debug/tests/test_diameter_gx")
set_tests_properties(test_diameter_gx PROPERTIES  LABELS "unit" TIMEOUT "30" _BACKTRACE_TRIPLES "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;149;add_test;/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;0;")
add_test(test_diameter_rx "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/build_debug/tests/test_diameter_rx")
set_tests_properties(test_diameter_rx PROPERTIES  LABELS "unit" TIMEOUT "30" _BACKTRACE_TRIPLES "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;168;add_test;/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;0;")
add_test(test_diameter_gy "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/build_debug/tests/test_diameter_gy")
set_tests_properties(test_diameter_gy PROPERTIES  LABELS "unit" TIMEOUT "30" _BACKTRACE_TRIPLES "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;187;add_test;/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;0;")
add_test(test_gy_service_units "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/build_debug/tests/test_gy_service_units")
set_tests_properties(test_gy_service_units PROPERTIES  LABELS "unit" TIMEOUT "30" _BACKTRACE_TRIPLES "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;206;add_test;/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;0;")
add_test(test_gy_mscc "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/build_debug/tests/test_gy_mscc")
set_tests_properties(test_gy_mscc PROPERTIES  LABELS "unit" TIMEOUT "30" _BACKTRACE_TRIPLES "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;225;add_test;/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;0;")
add_test(test_diameter_cx "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/build_debug/tests/test_diameter_cx")
set_tests_properties(test_diameter_cx PROPERTIES  LABELS "unit" TIMEOUT "30" _BACKTRACE_TRIPLES "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;244;add_test;/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;0;")
add_test(test_diameter_sh "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/build_debug/tests/test_diameter_sh")
set_tests_properties(test_diameter_sh PROPERTIES  LABELS "unit" TIMEOUT "30" _BACKTRACE_TRIPLES "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;263;add_test;/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;0;")
add_test(test_gtpv2_ie_parser "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/build_debug/tests/test_gtpv2_ie_parser")
set_tests_properties(test_gtpv2_ie_parser PROPERTIES  LABELS "unit" TIMEOUT "30" _BACKTRACE_TRIPLES "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;282;add_test;/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;0;")
add_test(test_gtpv2_bearer_context "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/build_debug/tests/test_gtpv2_bearer_context")
set_tests_properties(test_gtpv2_bearer_context PROPERTIES  LABELS "unit" TIMEOUT "30" _BACKTRACE_TRIPLES "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;301;add_test;/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;0;")
add_test(test_gtp_teid_manager "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/build_debug/tests/test_gtp_teid_manager")
set_tests_properties(test_gtp_teid_manager PROPERTIES  LABELS "unit" TIMEOUT "30" _BACKTRACE_TRIPLES "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;320;add_test;/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;0;")
add_test(test_sip_3gpp_headers "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/build_debug/tests/test_sip_3gpp_headers")
set_tests_properties(test_sip_3gpp_headers PROPERTIES  LABELS "unit" TIMEOUT "30" _BACKTRACE_TRIPLES "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;339;add_test;/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;0;")
add_test(test_sip_volte_vonr "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/build_debug/tests/test_sip_volte_vonr")
set_tests_properties(test_sip_volte_vonr PROPERTIES  LABELS "integration" TIMEOUT "30" _BACKTRACE_TRIPLES "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;358;add_test;/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;0;")
add_test(test_lte_attach_machine "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/build_debug/tests/test_lte_attach_machine")
set_tests_properties(test_lte_attach_machine PROPERTIES  LABELS "unit" TIMEOUT "30" _BACKTRACE_TRIPLES "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;378;add_test;/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;0;")
add_test(test_tunnel_lifecycle "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/build_debug/tests/test_tunnel_lifecycle")
set_tests_properties(test_tunnel_lifecycle PROPERTIES  LABELS "unit" TIMEOUT "30" _BACKTRACE_TRIPLES "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;398;add_test;/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;0;")
add_test(test_keepalive_aggregation "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/build_debug/tests/test_keepalive_aggregation")
set_tests_properties(test_keepalive_aggregation PROPERTIES  LABELS "unit" TIMEOUT "30" _BACKTRACE_TRIPLES "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;418;add_test;/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;0;")
add_test(test_handover_detection "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/build_debug/tests/test_handover_detection")
set_tests_properties(test_handover_detection PROPERTIES  LABELS "unit" TIMEOUT "30" _BACKTRACE_TRIPLES "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;438;add_test;/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;0;")
add_test(test_participant_detection "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/build_debug/tests/test_participant_detection")
set_tests_properties(test_participant_detection PROPERTIES  LABELS "unit" TIMEOUT "30" _BACKTRACE_TRIPLES "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;458;add_test;/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;0;")
add_test(test_ladder_generator "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/build_debug/tests/test_ladder_generator")
set_tests_properties(test_ladder_generator PROPERTIES  LABELS "unit" TIMEOUT "30" _BACKTRACE_TRIPLES "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;478;add_test;/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;0;")
add_test(test_tcp_reassembly "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/build_debug/tests/test_tcp_reassembly")
set_tests_properties(test_tcp_reassembly PROPERTIES  LABELS "unit" TIMEOUT "30" _BACKTRACE_TRIPLES "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;497;add_test;/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;0;")
add_test(test_tcp_ooo "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/build_debug/tests/test_tcp_ooo")
set_tests_properties(test_tcp_ooo PROPERTIES  LABELS "unit" TIMEOUT "30" _BACKTRACE_TRIPLES "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;516;add_test;/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;0;")
add_test(test_tcp_retransmission "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/build_debug/tests/test_tcp_retransmission")
set_tests_properties(test_tcp_retransmission PROPERTIES  LABELS "unit" TIMEOUT "30" _BACKTRACE_TRIPLES "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;535;add_test;/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;0;")
add_test(test_interface_detection "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/build_debug/tests/test_interface_detection")
set_tests_properties(test_interface_detection PROPERTIES  LABELS "unit" TIMEOUT "30" _BACKTRACE_TRIPLES "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;554;add_test;/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;0;")
add_test(test_multi_interface_pcapng "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/build_debug/tests/test_multi_interface_pcapng")
set_tests_properties(test_multi_interface_pcapng PROPERTIES  LABELS "integration" TIMEOUT "60" _BACKTRACE_TRIPLES "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;573;add_test;/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;0;")
add_test(test_subscriber_context "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/build_debug/tests/test_subscriber_context")
set_tests_properties(test_subscriber_context PROPERTIES  LABELS "unit" TIMEOUT "30" _BACKTRACE_TRIPLES "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;592;add_test;/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;0;")
add_test(test_context_lookup "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/build_debug/tests/test_context_lookup")
set_tests_properties(test_context_lookup PROPERTIES  LABELS "unit" TIMEOUT "30" _BACKTRACE_TRIPLES "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;611;add_test;/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;0;")
add_test(test_context_merge "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/build_debug/tests/test_context_merge")
set_tests_properties(test_context_merge PROPERTIES  LABELS "unit" TIMEOUT "30" _BACKTRACE_TRIPLES "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;630;add_test;/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;0;")
add_test(test_lte_attach_correlation "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/build_debug/tests/test_lte_attach_correlation")
set_tests_properties(test_lte_attach_correlation PROPERTIES  LABELS "integration" TIMEOUT "60" _BACKTRACE_TRIPLES "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;649;add_test;/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;0;")
add_test(test_volte_correlation "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/build_debug/tests/test_volte_correlation")
set_tests_properties(test_volte_correlation PROPERTIES  LABELS "integration" TIMEOUT "60" _BACKTRACE_TRIPLES "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;668;add_test;/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;0;")
add_test(test_volte_call "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/build_debug/tests/test_volte_call")
set_tests_properties(test_volte_call PROPERTIES  LABELS "unit" TIMEOUT "30" _BACKTRACE_TRIPLES "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;688;add_test;/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;0;")
add_test(test_volte_call_correlator "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/build_debug/tests/test_volte_call_correlator")
set_tests_properties(test_volte_call_correlator PROPERTIES  LABELS "unit" TIMEOUT "30" _BACKTRACE_TRIPLES "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;708;add_test;/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;0;")
add_test(test_volte_full_call "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/build_debug/tests/test_volte_full_call")
set_tests_properties(test_volte_full_call PROPERTIES  LABELS "integration" TIMEOUT "60" _BACKTRACE_TRIPLES "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;728;add_test;/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/tests/CMakeLists.txt;0;")
