if(EXISTS "/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/build_debug/tests/test_community_correlation[1]_tests.cmake")
  include("/Users/cemkaya/Developer/FlowVisualizerEnhancedDPI/build_debug/tests/test_community_correlation[1]_tests.cmake")
else()
  add_test(test_community_correlation_NOT_BUILT test_community_correlation_NOT_BUILT)
endif()
